### ISSUE TITLE
How to pretrain with Visual Genome?

### ISSUE THREAD

**Issue by qumengxue** [ubc-vision/RefTR#2]
Thanks for your excellent work. But how to pretrain on VG dataset with your code? I didn't find the config file or commands in README.

**Comment by jojo23333** [comment]
Hi, to pretrain you can use similar config with configs/refcoco/RefTR_refcoco.sh:
`srun python3.8 -u main_vg.py \
    --pretrained_model "./data/MODEL_ZOO/detr-r50-e632da11.pth"\
    --auto_resume \
    --num_feature_levels 1\
    --num_queries_per_phrase 1\
    --dataset vg\
    --train_split all\
    --test_split test\
    --dec_layers 6\
    --aux_loss \
    --img_size 640\
    --max_img_size 640\
    --epochs 15\
    --lr_drop_epochs 6\
    --batch_size 32\
    --lr_schedule MultiStepWarmupLR\
    --warm_up_epoch 3\
    --output_dir ${EXP_DIR} \
    ${PY_ARGS}`

Note You will need to download the annotation file for VisualGenome which removed val/test images in Refcoco dataset.

**Comment by qumengxue** [comment]
Thank you for your answer!
Additionally, could you please make the best "checkpoint.pth" publicly available?

**Comment by jojo23333** [comment]
Hi, sorry i don't quite keep the exact checkpoint coming from visual genome pretraining. But to reproduce pretrained model's result on refcoco you can try out this.checkpoints: https://github.com/ubc-vision/RefTR#pretrained-checkpoint-for-refcoco-resrec
These are checkpoints for RES and REC with visual genome pretraining.
