### ISSUE TITLE
no gref_umd folder under annotations_resc folder

### ISSUE THREAD

**Issue by seanzhuh** [ubc-vision/RefTR#4]
Hi, 

I've downloaded the data.zip and data.tar following ReSC's link, in your code, this link is at line 94 of datasets/grounding_datasets/resc_refer_dataset.py, which is https://drive.google.com/open?id=1cZI562MABLtAzM6YU4WmKPFFguuVr0lZ. When I unzip it, there is no gref_umd folder. 

Could you please help ?

**Comment by jojo23333** [comment]
you can checkout data preparation here: https://github.com/zyang-ur/ReSC the link should be: https://drive.google.com/file/d/1fVwdDvXNbH8uuq_pHD_o5HI7yqeuz0yS/view?usp=sharing. let me know if.you need further help.

**Comment by seanzhuh** [comment]
The provided link solved my problem, thanks ! Is it normal that val_accuracy_iou0.5 is fluctuating around 7 and there is no sign to increase at the first few epochs ?

**Comment by jojo23333** [comment]
Hi, I can not recall exactly, but if you are working with refcoco, it should converge at a reasonable speed.

**Comment by seanzhuh** [comment]
yes, refcoco is fine, but the evaluation accuracy of both refcoco+ and refcocog_umd seems weird, I've trained for 10 epochs using ImageNet initialization, yet the accuracy still fluctuates around 7.

**Comment by jojo23333** [comment]
hmm, that's weird, my experience is that refcoco/+/g 's converge should be similar.

**Comment by seanzhuh** [comment]
Could you provide the detection accuracy on RefCOCO/+/g with mask_head disabled, i.e., the first training phase with auxiliary loss on ?

**Comment by jojo23333** [comment]
Hi, one example of REC head only is shown in table 4, where refcoco+ validation ACC is lower by ~1.1%
I dug from my old log files and uncovered the testing performed at the last epoch of the first training phase, hope this could help:

REC only no VG pertaining acc:
- refcoco val/testA/testB: 81.08/85.16/76.24
- refcoco+ val/testA/testB:  70.02/74.41/61.08
- refcocog val/test: 68.21/68.96

**Comment by anony-seqtr** [comment]
wonderful, thanks for your help!

**Comment by seanzhuh** [comment]
wonderful, thanks for your help.
